# use limit range to start tensorboard in quotaed user namespace
# https://github.com/kubeflow/kubeflow/issues/7077
# https://github.com/kubeflow/pipelines/pull/9089#issuecomment-1499665846
# 
# use the following command to apply this configuration from your notebook terminal:
# kubectl -n <yournamespace> apply -f container-limit-range.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 500m
    defaultRequest:
      memory: 32Mi
      cpu: 10m
    type: Container